apiVersion: apps/v1
kind: Deployment
metadata:
  name: webdeploy
spec:
  selector:
    matchLabels:
      app: webdeploy
  template:
    metadata:
      labels:
        app: webdeploy
    spec:
      containers:
      - name: webapp
        image: nithishgwd/webapp:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80


---
apiVersion: v1
kind: Service
metadata:
  name: webdeploy-svc
spec:
  selector:
    app: webdeploy
  ports:
  - port: 8080
    targetPort: 80
  type: LoadBalancer
  externalIPs: 
  - 192.168.39.177
